### ISSUE TITLE
Display Issues

### ISSUE THREAD

**Issue by chimosky** [Hrishi1999/Dashboard.activity#1]
Ran activity and the stop button isn't showing, when I click on a particular day in the heatmap that has a lot of entries the window isn't scrollable.

Are activity instances supposed to be shown as files?. Should that be restricted to files of a particular mime type, as the terminal activity has no mime type but shows as a file.

![](https://user-images.githubusercontent.com/16203834/59043633-7d394580-8874-11e9-9791-eb6ce561e9aa.png)

You've done a great job, thanks.

**Comment by Hrishi1999** [comment]
Thanks for testing. What is your display resolution? The scrollbar isn't being displayed because of the tree view being stretched. Will fix it.

**Comment by chimosky** [comment]
> Thanks for testing. What is your display resolution?

16:9

> Are activity instances supposed to be shown as files?. Should that be restricted to files of a particular mime type, as the terminal activity has no mime type but shows as a file.

Can you answer this, thanks.

**Comment by Hrishi1999** [comment]
This activity was made with a 1280x720 display. It should support higher resolutions, but I haven't tested on lower resolution after some changes. 

Terminal activity, Chat activity are both shown as files. I could try to filter them out tomorrow (or find mime type which is responsible)

**Comment by quozl** [comment]
Please test on all common resolutions and aspect ratios.  Minimum for compatibility with Fedora 18 OLPC XO is 1200x900.

**Comment by Hrishi1999** [comment]
I've tested a couple of resolutions now (1152x864, 1280x720, 1200x900, 1600x900) and I couldn't seem to reproduce yet. Can you test again @chimosky (also, in the latest commit, active heatmap tiles are green, not blue so I guess you were testing on an older commit)? Thanks a lot!

**Comment by quozl** [comment]
Also test resizing displays.  This happens when an external monitor is plugged into a laptop, or when a virtual machine window is resized by the user.

**Comment by chimosky** [comment]
> I've tested a couple of resolutions now (1152x864, 1280x720, 1200x900, 1600x900) and I couldn't seem to reproduce yet. Can you test again @chimosky (also, in the latest commit, active heatmap tiles are green, not blue so I guess you were testing on an older commit)? Thanks a lot!

Tested and issue still persists but there's a slight difference now, when I select `Files` no items show as I have none but the stop button becomes visible but selection or `All` or `Older` hides it. My vm screen resolution is 1366x694.

**Comment by Hrishi1999** [comment]
I've fixed the TreeView column size issue. I ellipsized the title, the full title is visible as a tooltip. Please test the recent changes. Thanks :)

**Comment by chimosky** [comment]
Just tested, activity works as intended. Nice work. Thanks.
