### ISSUE TITLE
Source code review

### ISSUE THREAD

**Issue by quozl** [Hrishi1999/Dashboard.activity#3]
Source code was reviewed.

* [x] "Copyright 2019 Hrishi Patel" should be "Copyright (C) 2019  Hrishi Patel", see [How to apply these terms to your new programs](https://github.com/Hrishi1999/Dashboard.activity/blob/master/COPYING#L282),
* [x] `charts.py`, `readers.py` and `utils.py` are GPLv3+ but the main program is GPLv2+,
* [x] `pycha` is GPLv3+ but the main program is GPLv2+,
* [x] there's no copyright on `charts.py`, `readers.py`, and `utils.py`, this blocks the license,
* [x] a call to `gi.require_version` for Gdk is required for some operating system releases,
* [x] in `_build_heatmap` the use of week numbers to determine months is not portable to other years,
* [x] the exception handler in `_render_chart` covers a large body of code; it would be best to handle the exceptions in the lines that are affected, or test for the possibility they envisage,
* [x] there are 90 flake8 warnings or errors, and no `.flake8` file for the E402, see the Chat activity for how it can be configured,
* [x] sometimes signal callbacks are named with a trailing `_cb` and sometimes they aren't,
* [x] `activity.info` lacks a summary and some other metadata tags, README contains a useful summary,
* [x] there is an icon for Hello World included.

Hope that helps.

**Comment by Hrishi1999** [comment]
I will make the required changes. Will get back to you and mentors if I hit a roadblock. Thanks!

**Comment by Hrishi1999** [comment]
@quozl For `_build_heatmap`, the week number fits months for most of the years I tested.

**Comment by quozl** [comment]
I'm still a bit confused by the code in `_build_heatmap`, and don't like how it adds month names for translation.  Month names have already been translated for the underlying operating system.  Could you use the Locale Month Name `%b` format directive in strftime to avoid adding to translation?  Could you use the Week Number `%j` format directive in strftime in order to avoid that large if-else statement?

**Comment by quozl** [comment]
By the way, if you know any other languages, you might contribute translations to your own project.  Translations should go in the `po/` directory.  :grin:

**Comment by Hrishi1999** [comment]
@quozl Will do. I am also not using if-else statements anymore.

**Comment by Hrishi1999** [comment]
@quozl Also, I made modifications to the `_build_heatmap `code. No more if statements. I also tested with various years (2020, 21, 21, 23, 24), and the month names seem fine.

**Comment by quozl** [comment]
Thanks.
