### ISSUE TITLE
Activity icon is different

### ISSUE THREAD

**Issue by quozl** [Hrishi1999/Dashboard.activity#5]
Unlike other activities, the Dashboard activity has an activity icon without a title, description and share button.  A journal object is created, but the name cannot be changed within the activity.

**Comment by Hrishi1999** [comment]
Fixed. https://github.com/Hrishi1999/Dashboard.activity/commit/8cd61bf866ab56c1e26a082a255a0c9d08465b06
Edit: Issue accidentally closed, please reopen if required.

**Comment by quozl** [comment]
Thanks!
